// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_collectioner = "CgkIo8msrrcEEAIQDQ"; // <GPGSID>
        public const string achievement_real_purchase = "CgkIo8msrrcEEAIQDw"; // <GPGSID>
        public const string achievement_grasshopper = "CgkIo8msrrcEEAIQBg"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIo8msrrcEEAIQAQ"; // <GPGSID>
        public const string achievement_best_of_the_best = "CgkIo8msrrcEEAIQEA"; // <GPGSID>
        public const string achievement_enemy_fighter = "CgkIo8msrrcEEAIQCA"; // <GPGSID>
        public const string achievement_richman = "CgkIo8msrrcEEAIQBA"; // <GPGSID>
        public const string achievement_first_money = "CgkIo8msrrcEEAIQAw"; // <GPGSID>
        public const string achievement_first_fail = "CgkIo8msrrcEEAIQBw"; // <GPGSID>
        public const string achievement_jumper = "CgkIo8msrrcEEAIQDA"; // <GPGSID>
        public const string achievement_skilled = "CgkIo8msrrcEEAIQBQ"; // <GPGSID>
        public const string achievement_first_jump = "CgkIo8msrrcEEAIQAg"; // <GPGSID>
        public const string achievement_new_character = "CgkIo8msrrcEEAIQCQ"; // <GPGSID>
        public const string achievement_viewed_video = "CgkIo8msrrcEEAIQCw"; // <GPGSID>

}

